### ISSUE TITLE
Deprecation warning on iOS 7

### ISSUE THREAD

**Issue by ghost** [iGriever/TWSReleaseNotesView#7]
There is one deprecation warning shined by Xcode:

```
- (CGSize)sizeWithFont:(UIFont *)font constrainedToSize:(CGSize)size lineBreakMode:(NSLineBreakMode)lineBreakMode
```

On _TWSReleaseNotesView.m_ file.

**Comment by iGriever** [comment]
Yeah, I'm aware of that. That method is used in order to calculate the expected size for the release notes text, in the following way:

``` objective-c
    CGSize expectedLabelSize = [self.releaseNotesText sizeWithFont:self.releaseNotesFont constrainedToSize:maximumLabelSize lineBreakMode:NSLineBreakByWordWrapping];
```

The suggested way to do that, in iOS 7, is the following:

``` objective-c
    CGRect boundingRect = [self.releaseNotesText boundingR***W***S***:maximumLabelSize options:NSStringDrawingUsesLineFragmentOrigin attributes:@{NSFontAttributeName : self.releaseNotesFont} context:nil];
    CGSize expectedLabelSize = boundingRect.size;
```

I'm not writing the complete method signature due to NDA, but you can easily find what it is in the docs. Unfortunately, that API is not available before iOS 7 and there is no suggested alternative way to do that, so I could not include it in the current implementation.

I will update the implementation after iOS 7 official release.

Closing for now.
